@GymManagementSystem.Api_HostAddress = https://localhost:7094

POST {{GymManagementSystem.Api_HostAddress}}/api/exercise
Content-Type: application/json

{
  "name":"Triceps Single PushDown With Rope",
  "description":"Very Good For Triceps",
  "muscleGroup":"Triceps"
}

###

GET {{GymManagementSystem.Api_HostAddress}}/api/exercise?PageNumber=2

###

GET {{GymManagementSystem.Api_HostAddress}}/api/exercise/5

###

PUT {{GymManagementSystem.Api_HostAddress}}/api/exercise/5
Content-Type: application/json

{
   "name": "Shoulder Press",
  "description": "Overhead pressing exercise for front Dealt",
  "muscleGroup": "Shoulders"
}

###

GET {{GymManagementSystem.Api_HostAddress}}/api/membershipplan

###

@id=0
GET {{GymManagementSystem.Api_HostAddress}}/api/membershipplan/4

###

GET {{GymManagementSystem.Api_HostAddress}}/api/membershipplan/active

###

GET {{GymManagementSystem.Api_HostAddress}}/api/membershipplan/{{id}}

###

PUT {{GymManagementSystem.Api_HostAddress}}/api/membershipplan/{id}
Content-Type: application/json

{
  //UpdatePlanCommand
}

###

PUT {{GymManagementSystem.Api_HostAddress}}/api/membershipplan/4/toggle-status

###

POST {{GymManagementSystem.Api_HostAddress}}/api/membershipplan
Content-Type: application/json

{
    "name": "Basic",
    "description": "Access to gym equipment only",
    "price": 520.00,
    "durationInDays": 30
}

###

POST {{GymManagementSystem.Api_HostAddress}}/api/progresslog
Content-Type: application/json

{
    "weight": 65.5,
    "notes": "Feeling great!",
    "logDate": "2026-06-15"
}

###



###

PUT {{GymManagementSystem.Api_HostAddress}}/api/progresslog/2002
Content-Type: application/json

{
    "weight": 64.0,
    "notes": "Feeling great!",
    "logDate": "2026-06-15"
}

###

@progressLogId=0
DELETE {{GymManagementSystem.Api_HostAddress}}/api/progresslog/2002

###

GET {{GymManagementSystem.Api_HostAddress}}/api/progresslog?PageSize=4&PageNumber=2&SortColumn=weight&SortDirection=ASC

###

GET {{GymManagementSystem.Api_HostAddress}}/api/progresslog/me

###

GET {{GymManagementSystem.Api_HostAddress}}/api/progresslog/me

###

POST {{GymManagementSystem.Api_HostAddress}}/api/workoutplanexercises/5/exercises
Content-Type: application/json

{
  "exerciseId":5,
  "sets":2,
  "reps":10,
  "weight":50.0,
  "restTime":120.0
  
}

###

PUT {{GymManagementSystem.Api_HostAddress}}/api/workoutplanexercises/1
Content-Type: application/json

{
  "sets":5,
  "reps":10,
  "weight":60.0,
  "restTime":90.0
}

###

@workoutPlanId=0
GET {{GymManagementSystem.Api_HostAddress}}/api/workoutplanexercises/1/exercises

###

@workoutPlanExerciseId=0
DELETE {{GymManagementSystem.Api_HostAddress}}/api/workoutplanexercises/1002

###
